language: python
python:
  - 2.6
  - 2.7
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
before_script:
  - psql -c 'create database pickleback_test;' -U postgres
script: python manage.py test
