language: python
python:
  - 2.6
  - 2.7
before_script:
  - "cp local_settings.py.sample local_settings.py"
  - psql -c 'create database pickleback;' -U postgres
install: pip install -r requirements.txt
script: python manage.py test
